### PR TITLE
Fix Issue 26

### PR DESCRIPTION
**Pull request by computerfr33k**

### CODE REVIEW

**Comment by ochagata** [comment]
Tabs permission has already been removed, make sure the branches are up to date before making a pull request

**Comment by computerfr33k** [comment]
my bad. Want me to make a new pull request? Or doesn't git automatically know how to handle the merge changes.

**Comment by SergueiFedorov** [comment]
I'll just close this one and you can just make a new one. I'll merge it in once I get the request.

**Comment by ochagata** [comment]
merge dev into the branch and push again, and it will update on the pull request

**Comment by computerfr33k** [comment]
I noticed that this causes the extension to load on any tab that updates now. I will try and figure out a better solution.

**Pull request merged**
