### PR TITLE
Fix surguei toast rewrite

### LINKED ISSUE #88: Message Displays Any Time Page is Reloaded
This maybe an issue I created. But when I refresh the page entirely, the toast message comes back

### PR DESCRIPTION
**Pull request by computerfr33k**
Fixes #88.

Please test this on your end as well just to make sure all is working properly.
I also had to change the function so that it now requires you to pass the options object as a parameter.

### CODE REVIEW

**Comment by SergueiFedorov** [comment]
I'll check this out when I get home in about 20 min

**Comment by SergueiFedorov** [comment]
image

**Comment by SergueiFedorov** [comment]
I added remote tracking to your thread and checked it out. Then ran the BUILD_CHROME.py script

**Comment by computerfr33k** [comment]
This should only happen when using a slow connection because of the limitation of our main.js. Nothing I can do about this.

**Comment by SergueiFedorov** [comment]
Can you specify where the toast get's attached to? So for instance a lot of our code does this:

     $(html).appendTo($("body", window.parent.document));

As a way to ensure it get's attached to specific document (iFrame is considered a seperate HTML document, which is why this problem is happening)

**Comment by computerfr33k** [comment]
No, but the real problem is that our script is getting executed on both documents. We really should figure out a way to not execute on all frames if possible so that we are not running main twice.

**Comment by SergueiFedorov** [comment]
Try this:

https://github.com/SergueiFedorov/rateMyDePaul/commit/eca8f07784b42e406787929ddf3cc89c39df4df5

The popup stopped opening twice for me but I have no way to verify that it's actually working (since it seems to only happen on slow connections)

**Comment by SergueiFedorov** [comment]
Did we even fix the multiple popup issue yet?

**Pull request merged**
