### PR TITLE
Use HTML 5 Notifications

### PR DESCRIPTION
**Pull request by computerfr33k**

### CODE REVIEW

**Comment by computerfr33k** [comment]
Not sure why this can't merge automatically

**Comment by SergueiFedorov** [comment]
@ochagata knows how to do merges through the command line git. I have to do it in a sandbox before doing pull request merges on here with git bash.

**Comment by computerfr33k** [comment]
For some reason, I can now use chrome.notifications API. I think they finally added it into stable recently. I could use that instead of using HTML 5 notfications since we would need to ask for permission if using HTML 5.

**Comment by SergueiFedorov** [comment]
Is this is working order? Just making sure I can merge

**Comment by computerfr33k** [comment]
Should be.

On May 11, 2015 4:50:08 PM CDT, Serguei Fedorov <notifications@github.com> wrote:
>Is this is working order? Just making sure I can merge
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ochagata/rateMyPaul/pull/100#issuecomment-101059080

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by SergueiFedorov** [comment]
I merged and resolved this in my dev branch. I'll create a pull request from there

**Comment by SergueiFedorov** [comment]
Ok, obviously I have no idea what I am doing. How do we resolve this? Because it got resolved into my own fork, but when I try to pull requesting to the main repo it doesn't auto merge.

**Comment by computerfr33k** [comment]
Let me try making another pull request with just the Notification Changes from upstream

**Comment by computerfr33k** [comment]
Oh, this is actually when I was using HTML 5 for notifications. Let me use the chrome API since it will be better and not require the user to click to accept notifications.

**Pull request closed without merging**
